import { createI18n } from 'vue-i18n'

const messages = {
  en: {
    navigation: { cart: 'Cart', favourites: 'Favourites', admin: 'Backoffice', sales: 'Sales', products: 'Products', shop: 'Go to shop', language: 'Language', search: 'Search', openSearch: 'Open search', closeSearch: 'Close search', openMenu: 'Open menu', closeMenu: 'Close menu' },
    common: { add: 'Add to cart', edit: 'Edit', remove: 'Remove', total: 'Total', subtotal: 'Subtotal', taxes: 'Taxes (10%)', savings: 'Savings', quantity: 'Qty.', price: 'Price', continueShopping: 'Continue shopping', checkout: 'Proceed to checkout', close: 'Close', cancel: 'No, cancel', confirm: "Yes, I'm sure", removeAll: 'Remove all sales', image: 'Image', name: 'Name', description: 'Description', category: 'Category', stock: 'Stock', actions: 'Actions', loadingImage: 'Loading image...', uploading: 'Uploading', productImage: 'Product image', selectCategory: 'Select category', info: 'Info', breadcrumb: 'Breadcrumb', invoice: 'Invoice #{invoice}', viewOnGithub: 'Check on GitHub' },
    shop: { search: 'Search products', allCategories: 'All categories', noProducts: 'No products found', tryDifferentFilter: 'Try a different search or category.', storeEmpty: 'Store is empty', noProductsAdded: 'No products have been added yet', outOfStock: 'Out of stock', inStock: '{count} in stock', addedToCart: 'Added to your cart', cartReady: 'Your cart is ready', item: 'item', items: 'items', productNotFound: 'Product not found', addToWishlist: 'Add to wishlist', removeFromWishlist: 'Remove from wishlist', relatedProducts: 'Related products', productImageAlt: 'Product image', freshPicks: 'Fresh Picks for You', freshPicksPrimary: 'Fresh Picks', freshPicksSuffix: 'for You', heroDescription: 'Hottest Trends in Urban Fashion, Handpicked. Your Next Favorite Look Starts Here!', couponOffer: 'Use coupon for 10% OFF', couponCopied: 'Coupon copied to clipboard', wishlist: 'Your Wishlist', wishlistHelp: "Here you can see all the products you've added to your favorites list. Browse through and quickly find your favorite items!", wishlistEmptyTitle: 'Oops, nothing here...', wishlistEmptyMessage: 'Your favorites list is currently empty! Explore our products and add your preferred items here to keep them handy.', goHome: 'Go to the home page' },
    cart: { title: 'Cart', review: 'Review your order details in order to proceed with the checkout.', orderSummary: 'Order summary', emptyTitle: 'Oops! Nothing here', emptyMessage: 'No products have been added to the cart yet', goShopping: 'Go shopping now!', amount: 'Cart amount', voucherTitle: 'Vouchers', discountQuestion: 'Do you have a discount code?', enterCode: 'Enter code...', validating: 'Validating...', apply: 'Apply', couponInvalid: 'Coupon not valid', outOfStock: 'Product is out of stock', maximumReached: 'Maximum items reached', emptyCheckout: 'Your cart is empty', insufficientStock: '{name} no longer has enough stock' },
    checkout: { returnToCart: 'Return to cart', bankName: 'Vault Street Bank', securePayment: 'Secure payment', paymentHelp: 'Enter your card details to complete this demo purchase.', cardholder: 'Cardholder name', cardNumber: 'Card number', expiryDate: 'Expiry date', cvv: 'CVV', pay: 'Pay {total}', paySecurely: 'Pay securely', processing: 'Processing payment...', approved: 'Payment approved', orderPlaced: 'Your order has been placed successfully.', demoNotice: 'Demo gateway: card data is never stored.', cardholderRequired: 'Cardholder name is required', cardNumberRequired: 'Card number is required', cardNumberInvalid: 'Enter a valid 16-digit card number', expiryRequired: 'Expiry date is required', expiryInvalid: 'Enter a valid future expiry date', cvvRequired: 'CVV is required', cvvInvalid: 'CVV must contain 3 digits' },
    sales: { selectRange: 'Select a date range', selectRangeHelp: 'Choose a start and end date to see total sales.', noSales: 'There are no sales for the selected date range', noSalesHelp: 'Try selecting another range in the calendar.', confirmRemoval: 'Are you sure you want to delete all sales?', removed: 'Sales were removed', totalPaid: 'Total paid', discount: '{percentage}% discount' },
    calendar: { today: 'Today', yesterday: 'Yesterday', lastDays: 'Last {count} Days', thisMonth: 'This Month', lastMonth: 'Last Month' },
    products: { newProduct: 'New Product', editProduct: 'Edit Product', addProduct: 'Add Product', updateProduct: 'Update Product', productName: 'Product name', productDescription: 'Product description', productPrice: 'Product price', productUnits: 'Product units', nameRequired: 'Name is required', descriptionRequired: 'Description is required', categoryRequired: 'Category is required', priceRequired: 'Price is required', stockRequired: 'Stock is required', added: 'New product added', updated: 'Product updated', imported: 'Products imported', removed: 'Products were removed', removeSelected: 'Remove selected products', confirmRemoval: 'Are you sure you want to delete this product?', confirmBulkRemoval: 'Are you sure you want to delete all the products?', addNew: 'Add new product', emptyMessage: 'No products have been added to the store yet. Start by clicking the button below to add your first product and manage it easily from here.', startAdding: 'Start adding a new product', importDemo: 'Import demo content', importDemoQuestion: 'Import demo content?', importDemoHelp: "This will import the 12 demo products with images from the demo folder into the local mock database. It's advisable that the database is empty first.", importProducts: 'Import products', selectAll: 'Select all products', selectProduct: 'Select {name}', categorySneakers: 'Sneakers', categoryClothing: 'Clothing', categoryApparel: 'Accessories' }
  },
  es: {
    navigation: { cart: 'Carrito', favourites: 'Favoritos', admin: 'Backoffice', sales: 'Ventas', products: 'Productos', shop: 'Ir a la tienda', language: 'Idioma', search: 'Buscar', openSearch: 'Abrir búsqueda', closeSearch: 'Cerrar búsqueda', openMenu: 'Abrir menú', closeMenu: 'Cerrar menú' },
    common: { add: 'Añadir al carrito', edit: 'Editar', remove: 'Eliminar', total: 'Total', subtotal: 'Subtotal', taxes: 'Impuestos (10%)', savings: 'Ahorro', quantity: 'Cant.', price: 'Precio', continueShopping: 'Seguir comprando', checkout: 'Ir al pago', close: 'Cerrar', cancel: 'No, cancelar', confirm: 'Sí, estoy seguro', removeAll: 'Eliminar todas las ventas', image: 'Imagen', name: 'Nombre', description: 'Descripción', category: 'Categoría', stock: 'Existencias', actions: 'Acciones', loadingImage: 'Cargando imagen...', uploading: 'Subiendo', productImage: 'Imagen del producto', selectCategory: 'Selecciona una categoría', info: 'Información', breadcrumb: 'Migas de pan', invoice: 'Factura #{invoice}', viewOnGithub: 'Ver en GitHub' },
    shop: { search: 'Buscar productos', allCategories: 'Todas las categorías', noProducts: 'No se han encontrado productos', tryDifferentFilter: 'Prueba otra búsqueda o categoría.', storeEmpty: 'La tienda está vacía', noProductsAdded: 'Aún no se han añadido productos', outOfStock: 'Sin existencias', inStock: '{count} disponibles', addedToCart: 'Añadido al carrito', cartReady: 'Tu carrito está listo', item: 'artículo', items: 'artículos', productNotFound: 'Producto no encontrado', addToWishlist: 'Añadir a favoritos', removeFromWishlist: 'Quitar de favoritos', relatedProducts: 'Productos relacionados', productImageAlt: 'Imagen del producto', freshPicks: 'Novedades para ti', freshPicksPrimary: 'Novedades', freshPicksSuffix: 'para ti', heroDescription: 'Las últimas tendencias en moda urbana, elegidas para ti. ¡Tu próximo look favorito empieza aquí!', couponOffer: 'Usa el cupón y consigue un 10% de descuento', couponCopied: 'Cupón copiado al portapapeles', wishlist: 'Tu lista de deseos', wishlistHelp: 'Aquí puedes ver todos los productos que has añadido a favoritos. ¡Explora y encuentra rápidamente tus artículos favoritos!', wishlistEmptyTitle: 'Vaya, no hay nada aquí...', wishlistEmptyMessage: '¡Tu lista de favoritos está vacía! Explora nuestros productos y añade aquí los que prefieras para tenerlos a mano.', goHome: 'Ir a la página de inicio' },
    cart: { title: 'Carrito', review: 'Revisa los detalles de tu pedido para continuar con el pago.', orderSummary: 'Resumen del pedido', emptyTitle: '¡Vaya! No hay nada aquí', emptyMessage: 'Aún no se han añadido productos al carrito', goShopping: '¡Ir a comprar!', amount: 'Importe del carrito', voucherTitle: 'Cupones', discountQuestion: '¿Tienes un código de descuento?', enterCode: 'Introduce el código...', validating: 'Validando...', apply: 'Aplicar', couponInvalid: 'Cupón no válido', outOfStock: 'El producto no tiene existencias', maximumReached: 'Se ha alcanzado el máximo de artículos', emptyCheckout: 'El carrito está vacío', insufficientStock: '{name} ya no tiene existencias suficientes' },
    checkout: { returnToCart: 'Volver al carrito', bankName: 'Vault Street Bank', securePayment: 'Pago seguro', paymentHelp: 'Introduce los datos de tu tarjeta para completar esta compra de demostración.', cardholder: 'Nombre del titular', cardNumber: 'Número de tarjeta', expiryDate: 'Fecha de caducidad', cvv: 'CVV', pay: 'Pagar {total}', paySecurely: 'Pagar de forma segura', processing: 'Procesando pago...', approved: 'Pago aprobado', orderPlaced: 'Tu pedido se ha realizado correctamente.', demoNotice: 'Pasarela de demostración: los datos de la tarjeta no se guardan.', cardholderRequired: 'El nombre del titular es obligatorio', cardNumberRequired: 'El número de tarjeta es obligatorio', cardNumberInvalid: 'Introduce un número de tarjeta válido de 16 dígitos', expiryRequired: 'La fecha de caducidad es obligatoria', expiryInvalid: 'Introduce una fecha de caducidad futura válida', cvvRequired: 'El CVV es obligatorio', cvvInvalid: 'El CVV debe contener 3 dígitos' },
    sales: { selectRange: 'Selecciona un rango de fechas', selectRangeHelp: 'Elige una fecha de inicio y otra de fin para ver el total de ventas.', noSales: 'No hay ventas para el rango seleccionado', noSalesHelp: 'Prueba a seleccionar otro rango en el calendario.', confirmRemoval: '¿Seguro que quieres eliminar todas las ventas?', removed: 'Las ventas se han eliminado', totalPaid: 'Total pagado', discount: '{percentage}% de descuento' },
    calendar: { today: 'Hoy', yesterday: 'Ayer', lastDays: 'Últimos {count} días', thisMonth: 'Este mes', lastMonth: 'El mes pasado' },
    products: { newProduct: 'Nuevo producto', editProduct: 'Editar producto', addProduct: 'Añadir producto', updateProduct: 'Actualizar producto', productName: 'Nombre del producto', productDescription: 'Descripción del producto', productPrice: 'Precio del producto', productUnits: 'Unidades del producto', nameRequired: 'El nombre es obligatorio', descriptionRequired: 'La descripción es obligatoria', categoryRequired: 'La categoría es obligatoria', priceRequired: 'El precio es obligatorio', stockRequired: 'Las existencias son obligatorias', added: 'Nuevo producto añadido', updated: 'Producto actualizado', imported: 'Productos importados', removed: 'Los productos se han eliminado', removeSelected: 'Eliminar productos seleccionados', confirmRemoval: '¿Seguro que quieres eliminar este producto?', confirmBulkRemoval: '¿Seguro que quieres eliminar todos los productos?', addNew: 'Añadir producto', emptyMessage: 'Aún no se han añadido productos a la tienda. Empieza haciendo clic en el botón de abajo para añadir tu primer producto y gestionarlo desde aquí.', startAdding: 'Empezar a añadir un producto', importDemo: 'Importar contenido de demostración', importDemoQuestion: '¿Importar contenido de demostración?', importDemoHelp: 'Esto importará los 12 productos de demostración, con imágenes de la carpeta demo, a la base de datos local simulada. Es aconsejable que la base de datos esté vacía primero.', importProducts: 'Importar productos', selectAll: 'Seleccionar todos los productos', selectProduct: 'Seleccionar {name}', categorySneakers: 'Zapatillas', categoryClothing: 'Ropa', categoryApparel: 'Accesorios' }
  }
}

function getInitialLocale() {
  try {
    return localStorage.getItem('vue-shop-locale') === 'es' ? 'es' : 'en'
  } catch {
    return 'en'
  }
}

export const i18n = createI18n({ legacy: false, locale: getInitialLocale(), fallbackLocale: 'en', messages })

export function setLocale(locale) {
  i18n.global.locale.value = locale
  try {
    localStorage.setItem('vue-shop-locale', locale)
  } catch (error) {
    console.warn('i18n: could not persist locale', error)
  }
}
